framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:

            query.bus:

        transports:
            sync: 'sync://'
        routing:
            App\Blog\Application\UseCase\Command\Post\CreatePostCommand: [sync]
            App\Blog\Application\Query\Post\FindAllPublishedPostQueryHandler: [sync]
