admin_controller:
    resource: '../../src/App/UI/Controller/Admin'
    type: annotation

client_controller:
    resource: '../../src/App/UI/Controller/Client'
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
