parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Blog\:
        resource: '../src/Blog/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

#    App\Blog\Admin\Api\Controller\:
#        resource: '../app/blog/admin/api/src/Controller'
#        tags: ['controller.service_arguments']

#    App\Blog\Client\Api\Controller\:
#        resource: '../app/blog/client/api/src/Controller'
#        tags: ['controller.service_arguments']
