parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

    App\Blog\UI\Controller\Admin\:
        resource: '../src/Blog/UI/Controller/Admin'
        tags: ['controller.service_arguments']

    App\Blog\Application\UseCase\Command\Post\:
        resource: '%kernel.project_dir%//src/Blog/Application/UseCase/Command/Post/*CommandHandler.php'
        public: true
        autowire: true
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    App\Blog\Application\Query\Post\:
        resource: '%kernel.project_dir%//src/Blog/Application/Query/Post/*QueryHandler.php'
        public: true
        autowire: true
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }
