parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Blog\:
        resource: '../src/Blog/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Blog\Admin\:
        resource: '../app/blog/admin/src/*'

    App\Blog\Client\:
        resource: '../app/blog/client/src/*'

    App\Blog\Admin\Controller\:
        resource: '../app/blog/admin/src/Controller'
        tags: ['controller.service_arguments']

    App\Blog\Client\Controller\:
        resource: '../app/blog/client/src/Controller'
        tags: ['controller.service_arguments']
