version: '3'

services:
    nginx:
        image: nginx:alpine
        depends_on:
          - client
        ports:
            - 80:80
        volumes:
            - './.docker/nginx/blog.conf:/etc/nginx/nginx.conf'
        links:
          - admin
          - client

    admin:
        image: php:8-0-cqrs-blog
        build:
            dockerfile: Dockerfile
            context: .docker/apache2
        volumes:
            - './blog:/var/www/html'
            - './.docker/apache2/admin.conf:/etc/apache2/sites-enabled/000-default.conf'

    client:
        image: php:8-0-cqrs-blog
        depends_on:
          - admin
        volumes:
            - './blog:/var/www/html'
            - './.docker/apache2/client.conf:/etc/apache2/sites-enabled/000-default.conf'

    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=YOUR_DB_PASSWORD
            - MYSQL_DATABASE=cqrs-blog-dev
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - '3306:3306'

volumes:
  mysql:
